# Generated by Django 4.0.4 on 2022-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesapp',
            name='type_file',
            field=models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG')], default='', max_length=4),
        ),
    ]
