# Generated by Django 4.0.4 on 2022-06-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='extra',
            field=models.CharField(choices=[('general', 'Descripción general'), ('files', 'Archivos')], default='', max_length=10),
        ),
    ]
