# Generated by Django 4.0.4 on 2022-04-28 01:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificación')),
                ('cellphone', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('biography', models.TextField(verbose_name='Biografía')),
                ('photo', models.CharField(max_length=255, verbose_name='Foto')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('evaluator', 'Evaluador'), ('writer', 'Escritor')], max_length=9)),
                ('show_intro', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
